#!/usr/bin/env python3
"""One-shot builder for data/source.jsonl. Not required at train time."""

from __future__ import annotations

import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "source.jsonl"

# Each row: (user_message_without_tag, label). Labels are 2-5 words, no punctuation.
PAIRS: list[tuple[str, str]] = [
    ("How do I configure Docker networking?", "Docker Networking"),
    ("What's the difference between an AI agent and an AI model?", "Agents vs Models"),
    ("How can I deploy a Nuxt application to Cloudflare Workers?", "Nuxt Cloudflare Deployment"),
    ("Why won't my PostgreSQL connection work?", "PostgreSQL Connection Issue"),
    ("How do I fine-tune a small language model?", "LLM Fine Tuning"),
    ("How do I configure a Cloudflare tunnel with Docker?", "Cloudflare Docker Setup"),
    ("git rebase vs merge which should I use", "Git Rebase vs Merge"),
    ("k8s pod keeps crashing with OOMKilled", "Kubernetes OOM Crash"),
    ("ssh permission denied publickey on a new laptop", "SSH Public Key Issue"),
    ("my nginx reverse proxy returns 502", "Nginx Reverse Proxy Error"),
    ("explain mcp servers like I'm new to this", "MCP Server Basics"),
    ("can you help me pick a database for a saas billing app", "SaaS Database Choice"),
    ("how do I rotate AWS access keys without downtime", "AWS Key Rotation"),
    ("tailwind styles not applying in a nuxt 3 app", "Nuxt Tailwind Issue"),
    ("what's a durable object on cloudflare", "Cloudflare Durable Objects"),
    ("my laptop fan is screaming while compiling rust", "Laptop Thermal Throttling"),
    ("best way to meal prep chicken for the week", "Weekly Chicken Mealprep"),
    ("is it cheaper to fly into newark or jfk for a manhattan trip", "NYC Airport Choice"),
    ("how do I dispute a double charge on my visa", "Visa Double Charge"),
    ("remind me how compound interest works in a high yield savings account", "Compound Interest Basics"),
    ("strapi webhook not firing after publish", "Strapi Webhook Failure"),
    ("how do I add turnstile to a workers form", "Turnstile Form Setup"),
    ("python venv vs uv which should I use in 2026", "Python uv vs venv"),
    ("why is my docker compose postgres volume empty after restart", "Docker Volume Persistence"),
    ("github actions failing on pnpm install cache", "GitHub Actions Cache"),
    ("how do I write an openapi spec for this endpoint", "OpenAPI Spec Writing"),
    ("jwt vs session cookies for a b2b dashboard", "JWT vs Sessions"),
    ("my raspberry pi won't boot after a power cut", "Raspberry Pi Boot"),
    ("what's the difference between rag and fine tuning", "RAG vs Fine Tuning"),
    ("how do I self host ollama on linux", "Ollama Linux Setup"),
    ("can I run kubernetes on a single node for a homelab", "Single Node Kubernetes"),
    ("help me name this grocery list app without it sounding generic", "App Naming Help"),
    ("what's a good standup format for a 4 person team", "Standup Meeting Format"),
    ("my sourdough starter smells like acetone", "Sourdough Starter Issue"),
    ("should I refinance my mortgage if rates dropped half a point", "Mortgage Refinance Decision"),
    ("how do I set up fail2ban on ubuntu", "Ubuntu Fail2ban Setup"),
    ("cloudflare pages vs workers which for a static site", "Pages vs Workers"),
    ("typescript generic constraints keep erroring", "TypeScript Generic Constraints"),
    ("how do I stream llm tokens to the browser", "LLM Token Streaming"),
    ("what's an mcp tool versus a resource", "MCP Tools vs Resources"),
    ("postgres sequence is out of sync after a restore", "Postgres Sequence Repair"),
    ("docker buildx multi arch image for arm64", "Docker Multiarch Build"),
    ("how do I revoke a leaked github pat", "GitHub PAT Revocation"),
    ("explain hex architecture without the jargon", "Hexagonal Architecture Basics"),
    ("my wifi drops every time the microwave runs", "Wifi Microwave Interference"),
    ("best carry on backpack for a 10 day europe trip", "Travel Backpack Choice"),
    ("how do I cancel an unused adobe subscription", "Adobe Subscription Cancel"),
    ("what's the difference between gross margin and markup", "Margin vs Markup"),
    ("linux permission denied even with sudo on a mounted drive", "Linux Mount Permissions"),
    ("how do I add oauth to a hono api", "Hono OAuth Setup"),
    ("celery worker not picking up redis tasks", "Celery Redis Tasks"),
    ("why does my spa show a blank page after deploy", "SPA Blank Deploy"),
    ("help debug cors from localhost to a workers api", "CORS Localhost Debug"),
    ("what's a vector clock in distributed systems", "Vector Clock Basics"),
    ("how do I set up a cloudflare zero trust access app", "Cloudflare Access Setup"),
    ("my mechanical keyboard double types letters", "Keyboard Double Typing"),
    ("is it safe to eat leftover rice from yesterday", "Leftover Rice Safety"),
    ("how do I split rent fairly with roommates", "Roommate Rent Split"),
    ("git detached head how do I get back", "Git Detached Head"),
    ("github codespaces vs local devcontainer", "Codespaces vs Devcontainer"),
    ("how do I monitor disk io on linux", "Linux Disk IO"),
    ("kustomize vs helm for a small cluster", "Kustomize vs Helm"),
    ("what's the difference between gpt and a classifier", "GPT vs Classifier"),
    ("how do I log structured json from a python worker", "Python JSON Logging"),
    ("sqlite locked database in a fastapi app", "SQLite Database Locked"),
    ("how do I add 2fa to my github org", "GitHub Org 2FA"),
    ("explain event sourcing like I ship crud apps", "Event Sourcing Intro"),
    ("my nas is clicking loudly is that bad", "NAS Clicking Noise"),
    ("flight to lisbon with a 40 minute layover in madrid", "Tight Madrid Layover"),
    ("how do I make a decent carbonara without cream", "Carbonara Without Cream"),
    ("what's a good invoice cadence for a freelance designer", "Freelance Invoice Cadence"),
    ("iptables vs nftables in 2026", "iptables vs nftables"),
    ("how do I pin a python dependency with uv", "uv Dependency Pinning"),
    ("wrangler deploy fails with binding not found", "Wrangler Binding Error"),
    ("how do I test webhooks locally with cloudflare tunnels", "Tunnel Webhook Testing"),
    ("redis cache stampede how do I stop it", "Redis Cache Stampede"),
    ("what's the difference between oidc and saml", "OIDC vs SAML"),
    ("my gpu shows nvidia-smi failed in a container", "Container GPU Access"),
    ("how do I write a good rfc for a schema change", "Schema Change RFC"),
    ("can an agent call multiple mcp servers in one turn", "Agents Multiple MCP"),
    ("how do I shrink a docker image under 50mb", "Docker Image Size"),
    ("github dependabot noise is drowning real alerts", "Dependabot Alert Noise"),
    ("why is my spa hydrating twice in nuxt", "Nuxt Double Hydration"),
    ("how do I set up mtls between services", "Service mTLS Setup"),
    ("laptop battery drains overnight on linux", "Linux Battery Drain"),
    ("best way to pack liquids through tsa", "TSA Liquids Packing"),
    ("how do I roast vegetables so they actually brown", "Roasting Vegetables Tips"),
    ("should I take the 401k match or pay debt first", "401k vs Debt"),
    ("how do I rotate secrets in kubernetes", "Kubernetes Secret Rotation"),
    ("what's a sidecar proxy in a service mesh", "Sidecar Proxy Basics"),
    ("my prisma migrate failed halfway", "Prisma Migrate Failure"),
    ("how do I add rate limits on cloudflare", "Cloudflare Rate Limits"),
    ("llm outputs markdown when I asked for json", "LLM JSON Format"),
    ("how do I eval a prompt change without a huge dataset", "Prompt Eval Basics"),
    ("git blame shows the wrong author after rebase", "Git Blame After Rebase"),
    ("how do I expose a local mcp server to claude", "Local MCP Exposure"),
    ("my usb c hub won't charge and display at once", "USB Hub Power Issue"),
    ("what's a good first linux distro for a windows refugee", "First Linux Distro"),
    ("how do I cost an api per million tokens", "Token Cost Estimate"),
    ("help me debug a hanging postgres vacuum", "Postgres Vacuum Hang"),
    ("how do I set up github environments for staging", "GitHub Staging Environments"),
    ("what's the difference between cqrs and just splitting reads", "CQRS vs Read Split"),
    ("my espresso tastes sour even with a finer grind", "Sour Espresso Debug"),
    ("how do I negotiate a software salary band", "Salary Band Negotiation"),
    ("can I run d1 locally like production", "D1 Local Development"),
    ("how do I add a custom domain on cloudflare pages", "Pages Custom Domain"),
    ("k8s ingress nginx vs cloudflare tunnel", "Ingress vs Tunnel"),
    ("what's a tool calling loop in an agent", "Agent Tool Loop"),
    ("how do I redact pii from logs", "Log PII Redaction"),
    ("my mechanical drive is smarter than my ssd in this old laptop", "HDD vs SSD Laptop"),
    ("how do I plan a 3 day tokyo itinerary without overbooking", "Tokyo Three Day Plan"),
    ("is almond milk ok in a bechamel", "Almond Milk Bechamel"),
    ("how do I track personal net worth simply", "Simple Net Worth"),
    ("selinux is blocking my nginx on fedora", "SELinux Nginx Block"),
    ("how do I use ruff in pre commit", "Ruff Pre Commit"),
    ("what's the difference between workers kv and d1", "KV vs D1"),
    ("my graphql resolver n plus one is killing us", "GraphQL N Plus One"),
    ("how do I rotate jwt signing keys", "JWT Key Rotation"),
    ("explain backpressure in a queue", "Queue Backpressure"),
    ("gpu memory fragmentation during training", "GPU Memory Fragmentation"),
    ("how do I host a private npm registry", "Private npm Registry"),
    ("github rulesets vs branch protection", "Rulesets vs Protection"),
    ("how do I stream audio from a worker", "Workers Audio Streaming"),
    ("what's a context window and why did my agent forget", "Context Window Limits"),
    ("my docker desktop on linux is painfully slow", "Docker Desktop Slow"),
    ("how do I set up wireguard between two vps", "WireGuard VPS Setup"),
    ("can I fine tune smollm with lora on a 3080", "SmolLM LoRA Training"),
    ("how do I write a postmortem without blame", "Blameless Postmortem"),
    ("the office printer only works for windows users", "Printer Driver Issue"),
    ("best vegetarian protein for meal prep", "Vegetarian Meal Prep"),
    ("how do I avoid atm fees abroad", "Foreign ATM Fees"),
    ("systemd service won't stay running", "Systemd Service Crash"),
    ("how do I cache nuxt payloads on cloudflare", "Nuxt Cloudflare Cache"),
    ("what's the difference between grpc and rest", "gRPC vs REST"),
    ("my oauth redirect uri mismatch in production", "OAuth Redirect Mismatch"),
    ("how do I shard a postgres table later", "Postgres Table Sharding"),
    ("agent retries the same failing tool forever", "Agent Retry Loop"),
    ("how do I add tracing with otel", "OpenTelemetry Tracing"),
    ("laptop won't resume from suspend on fedora", "Fedora Suspend Resume"),
    ("how do I get a schengen visa appointment faster", "Schengen Visa Appointment"),
    ("why is my homemade yogurt watery", "Watery Yogurt Fix"),
    ("should I use a roth or traditional ira", "Roth vs Traditional IRA"),
    ("how do I set ulimits for a high connection server", "Linux Ulimit Tuning"),
    ("wrangler types generation for bindings", "Wrangler Binding Types"),
    ("how do I paginate a huge postgres table", "Postgres Pagination"),
    ("github merge queue vs required checks", "Merge Queue vs Checks"),
    ("what's a feature flag vs an experiment", "Flags vs Experiments"),
    ("how do I quantize a gguf to q4 k m", "GGUF Q4 Quantization"),
    ("my tls cert expired on a forgotten subdomain", "Expired TLS Certificate"),
    ("how do I design a webhook retry policy", "Webhook Retry Policy"),
    ("can mcp expose a database safely", "MCP Database Safety"),
    ("how do I stop docker from filling the disk", "Docker Disk Cleanup"),
    ("what's eventual consistency in plain words", "Eventual Consistency Basics"),
    ("my webcam is inverted after an update", "Inverted Webcam Fix"),
    ("best street food in mexico city for a first visit", "Mexico City Street Food"),
    ("how do I prove a freelance expense for taxes", "Freelance Expense Proof"),
    ("apparmor vs selinux which should I learn", "AppArmor vs SELinux"),
    ("how do I bump node in a monorepo without breaking ci", "Monorepo Node Upgrade"),
    ("cloudflare cache everything is serving stale html", "Cloudflare Stale Cache"),
    ("how do I model roles and permissions in sql", "SQL Roles Permissions"),
    ("what's the difference between embeddings and tokens", "Embeddings vs Tokens"),
    ("how do I run playwright in github actions", "Playwright GitHub Actions"),
    ("my zfs pool is degraded one disk", "ZFS Degraded Pool"),
    ("how do I pack a suit in a carry on", "Packing a Suit"),
    ("why did my mayonnaise split", "Split Mayonnaise Fix"),
    ("how do I set a personal budget that I actually follow", "Personal Budget Habit"),
    ("journald logs eating disk how do I cap them", "Journald Disk Cap"),
    ("how do I add a health check to a worker", "Worker Health Check"),
    ("neo4j vs postgres for a graph-ish product", "Neo4j vs Postgres"),
    ("how do I implement pkce for oauth", "OAuth PKCE Setup"),
    ("what's a saga in microservices", "Microservice Saga Pattern"),
    ("lora vs full finetune for a 135m model", "LoRA vs Full Finetune"),
    ("how do I pin github action versions", "Pin GitHub Actions"),
    ("my ipv6 is broken but ipv4 works", "IPv6 Connectivity Issue"),
    ("how do I write evals for a labeling model", "Labeling Model Evals"),
    ("agent needs a human approval step", "Agent Human Approval"),
    ("how do I backup d1", "D1 Backup Strategy"),
    ("the bios clock is wrong after a cmos battery swap", "BIOS Clock Battery"),
    ("how do I find quiet cafes in paris to work", "Paris Work Cafes"),
    ("can I freeze leftover chili", "Freezing Leftover Chili"),
    ("how do I read a cap table", "Cap Table Basics"),
    ("how do I enable bbr congestion control", "Linux BBR Setup"),
    ("nuxt server routes vs workers entry", "Nuxt vs Workers Routes"),
    ("how do I detect n plus one in prisma", "Prisma N Plus One"),
    ("what's scim provisioning", "SCIM Provisioning Basics"),
    ("how do I keep prompts out of git", "Secret Prompt Hygiene"),
    ("gguf vs safetensors for ollama", "GGUF vs Safetensors"),
    ("my bluetooth mouse lags on linux", "Linux Bluetooth Mouse"),
    ("how do I transfer a domain to cloudflare", "Cloudflare Domain Transfer"),
    ("what's a circuit breaker in an api", "API Circuit Breaker"),
    ("how do I train on completion tokens only", "Completion Only Loss"),
    ("github copilot vs a local 135m model", "Copilot vs Local Model"),
    ("how do I set up a staging db from prod dumps", "Staging From Prod Dump"),
    ("my ssd is at 100 percent and the laptop crawls", "Full SSD Slowdown"),
    ("how do I tip in japan", "Tipping In Japan"),
    ("how do I keep brown sugar from turning into a brick", "Brown Sugar Storage"),
    ("what's a burn multiple for a saas", "SaaS Burn Multiple"),
    ("how do I chroot into a broken ubuntu", "Ubuntu Chroot Recovery"),
    ("hono vs itty router on workers", "Hono vs Itty Router"),
    ("how do I version a public rest api", "REST API Versioning"),
    ("what's the difference between rbac and abac", "RBAC vs ABAC"),
    ("how do I stop an llm from leaking the system prompt", "System Prompt Leakage"),
    ("my qemu vm has no network", "QEMU Network Issue"),
    ("how do I use cloudflare r2 with a custom domain", "R2 Custom Domain"),
    ("what's an embedding model vs a chat model", "Embedding vs Chat Model"),
    ("how do I bisect a bad git commit", "Git Bisect Usage"),
    ("the laptop trackpad clicks but doesn't move", "Trackpad Click Issue"),
    ("how do I get around a 6 hour layover in istanbul", "Istanbul Layover Plan"),
    ("how do I make stock from a roast chicken carcass", "Chicken Stock From Carcass"),
    ("should I pay points to buy down a mortgage rate", "Mortgage Points Decision"),
    ("how do I enable unattended upgrades safely", "Unattended Upgrades Setup"),
    ("workers cron trigger vs queue consumer", "Cron vs Queue Workers"),
    ("how do I add idempotency keys to payments", "Payment Idempotency Keys"),
    ("what's a context graph for agents", "Agent Context Graph"),
    ("how do I convert huggingface to gguf", "Hugging Face to GGUF"),
    ("my raid 1 is rebuilding forever", "RAID Rebuild Stall"),
    ("how do I set up dkim for a domain", "DKIM Domain Setup"),
    ("what's a good definition of done for a tiny team", "Definition of Done"),
    ("how do I keep a conversation label consistent", "Consistent Chat Labels"),
    ("the office vpn blocks docker hub", "VPN Blocks Docker Hub"),
    ("how do I roast coffee at home without a dedicated roaster", "Home Coffee Roasting"),
    ("what's an arr vs mrr", "ARR vs MRR"),
    ("how do I recover a deleted linux partition", "Linux Partition Recovery"),
    ("nuxt i18n routing is duplicating locales", "Nuxt i18n Routing"),
    ("how do I store refresh tokens securely", "Secure Refresh Tokens"),
    ("what's tool choice auto vs required", "LLM Tool Choice"),
    ("how do I run trl sft on a conversational dataset", "TRL SFT Conversations"),
    ("my thunderbolt dock disconnects when I close the lid", "Dock Lid Disconnect"),
    ("how do I get a refund on a nonrefundable hotel", "Hotel Refund Request"),
    ("how do I keep cilantro from wilting in a day", "Cilantro Storage"),
    ("should I incorporate as an llc for freelance work", "Freelance LLC Decision"),
    ("how do I tune swappiness on a 64gb machine", "Linux Swappiness Tuning"),
    ("cloudflare waiting room for a launch", "Cloudflare Waiting Room"),
    ("how do I design a tenancy model for b2b saas", "B2B Tenancy Model"),
    ("what's a reward model in rlhf", "RLHF Reward Model"),
    ("how do I merge a lora into the base model", "Merge LoRA Adapter"),
    ("github wiki vs a docs site", "Wiki vs Docs Site"),
    ("my fan curve is silent then jet engine", "Laptop Fan Curve"),
    ("how do I use a travel esim", "Travel eSIM Setup"),
    ("how do I proof bread in a cold kitchen", "Cold Kitchen Proofing"),
    ("what's a good default savings rate", "Default Savings Rate"),
    ("how do I debug a segfault in a python c extension", "Python C Segfault"),
    ("workers ai vs a local ollama box", "Workers AI vs Ollama"),
    ("how do I add row level security in postgres", "Postgres Row Security"),
    ("what's the difference between a skill and a tool", "Skills vs Tools"),
    ("how do I keep evals from overfitting prompts", "Eval Overfit Prevention"),
    ("the bios update failed and the machine is bricked", "Failed BIOS Update"),
    ("how do I find a last minute rental car", "Last Minute Rental Car"),
    ("how do I cook dried beans without a long soak", "No Soak Beans"),
    ("what's dilution in a seed round", "Seed Round Dilution"),
    ("how do I set up a recursive dns resolver", "Recursive DNS Setup"),
    ("hono middleware order is surprising me", "Hono Middleware Order"),
    ("how do I revoke oauth apps org wide", "Org OAuth Revocation"),
    ("what's a mixture of experts in plain english", "Mixture of Experts"),
    ("how do I keep a small model from rambling", "Stop Model Rambling"),
    ("my nvme is not detected in the bios", "NVMe BIOS Detection"),
    ("how do I use ollama from another app", "Ollama App Integration"),
    ("the hotel wifi captive portal breaks wireguard", "Captive Portal VPN"),
    ("how do I make miso soup that isn't sad", "Better Miso Soup"),
    ("what's a good emergency fund size", "Emergency Fund Size"),
    ("how do I strace a hanging process", "strace Hanging Process"),
    ("nuxt image optimization on workers", "Nuxt Image Workers"),
    ("how do I rotate a kms key used by the app", "KMS Key Rotation"),
    ("what's function calling versus json mode", "Function Calling vs JSON"),
    ("how do I version a lora adapter", "LoRA Adapter Versioning"),
    ("github packages vs npmjs for private pkgs", "GitHub Packages vs npm"),
    ("my displayport to hdmi adapter has no audio", "DisplayPort HDMI Audio"),
    ("how do I pack camera gear for a flight", "Flying With Camera Gear"),
    ("how do I keep avocados from browning", "Avocado Browning"),
    ("what's a good pricing page for a prosumer tool", "Prosumer Pricing Page"),
    ("how do I enable fsync off for a throwaway postgres", "Postgres fsync Off"),
    ("cloudflare bot fight mode blocking our tests", "Bot Fight False Positive"),
    ("how do I model credits in a saas", "SaaS Credit Model"),
    ("what's speculative decoding", "Speculative Decoding"),
    ("how do I keep system prompts short for a 135m model", "Short System Prompts"),
    ("the laptop hinge is cracking the chassis", "Laptop Hinge Crack"),
    ("how do I get tsa precheck", "TSA Precheck Signup"),
    ("how do I make granola that actually clumps", "Clumpy Granola"),
    ("should I max hsa before 401k", "HSA vs 401k"),
    ("how do I drop caches on linux safely", "Linux Drop Caches"),
    ("workers hyperdrive to neon", "Hyperdrive Neon Setup"),
    ("how do I add passkeys to a web app", "WebAuthn Passkey Setup"),
    ("what's a world model versus an llm", "World Model vs LLM"),
    ("how do I continue sft from a merged checkpoint", "Continue From Merged"),
    ("github issue forms vs a linear intake", "Issue Forms vs Linear"),
    ("my usb ethernet dongle dies under load", "USB Ethernet Dropout"),
    ("how do I find a quiet hotel near a train station", "Hotel Near Station"),
    ("how do I keep basil alive on a windowsill", "Windowsill Basil Care"),
    ("what's a good default hourly rate for a senior engineer", "Senior Engineer Rate"),
    ("how do I use bpftrace for latency", "bpftrace Latency"),
    ("nuxt content vs a headless cms", "Nuxt Content vs CMS"),
    ("how do I expire stale sessions server side", "Server Session Expiry"),
    ("what's chain of thought vs just answering", "Chain of Thought"),
    ("how do I package a gguf with ollama", "Ollama GGUF Package"),
    ("the ssd firmware update wants a windows tool", "SSD Firmware Windows"),
    ("how do I change a flight after a delay", "Flight Change After Delay"),
    ("how do I pickle red onions quickly", "Quick Pickled Onions"),
    ("what's a safe withdrawal rate in retirement", "Safe Withdrawal Rate"),
    ("how do I remap caps lock to escape on wayland", "Wayland Caps Remap"),
    ("cloudflare images vs r2 plus a worker", "Images vs R2 Worker"),
    ("how do I design an audit log", "Audit Log Design"),
    ("what's a tokenizer and why does length differ", "Tokenizer Length Basics"),
    ("how do I keep a labeling model from adding quotes", "Stop Label Quotes"),
    ("github codespaces spend is surprising", "Codespaces Cost Spike"),
    ("my thunderbolt 4 enclosure is flaky", "Thunderbolt Enclosure Flake"),
    ("how do I rent an apartment with no us credit", "Rent Without Credit"),
    ("how do I keep tortillas from molding", "Tortilla Storage"),
    ("what's a good default runway target", "Startup Runway Target"),
    ("how do I enable hugepages for postgres", "Postgres Hugepages"),
    ("workers for platforms vs a single worker", "Workers for Platforms"),
    ("how do I add scim to our saas", "SaaS SCIM Support"),
    ("what's distillation for small models", "Model Distillation"),
    ("how do I install bros into ollama from git", "Bros Ollama Git Install"),
    ("the laptop keyboard ghosting in games", "Keyboard Ghosting"),
    ("how do I get a real bed on a long haul", "Long Haul Sleep"),
    ("how do I make overnight oats not gluey", "Overnight Oats Texture"),
    ("should I keep a taxable brokerage too", "Taxable Brokerage Role"),
    ("how do I inspect systemd cgroup memory", "systemd Cgroup Memory"),
    ("nuxt layer for a design system", "Nuxt Design System Layer"),
    ("how do I rotate a leaked stripe key", "Stripe Key Rotation"),
    ("what's a mixture of agents", "Mixture of Agents"),
    ("how do I add a new task tag to bros", "Bros New Task Tag"),
    ("github fine grained tokens vs classic", "Fine Grained vs Classic PAT"),
    ("my usb dac needs to be replugged after sleep", "USB DAC After Sleep"),
    ("how do I get a visa photo that they accept", "Visa Photo Requirements"),
    ("how do I keep brown butter from burning", "Brown Butter Control"),
    ("what's a good default discount rate in npv", "NPV Discount Rate"),
    ("how do I use tc to simulate latency", "tc Latency Simulation"),
    ("cloudflare zaraz vs a tag manager", "Zaraz vs Tag Manager"),
    ("how do I design a public status page", "Status Page Design"),
    ("what's kv cache in transformers", "Transformer KV Cache"),
    ("how do I keep labels to five words", "Five Word Labels"),
    ("the bios secure boot blocks my distro", "Secure Boot Distro"),
    ("how do I find a direct flight with extra legroom", "Legroom Direct Flight"),
    ("how do I make labneh at home", "Homemade Labneh"),
    ("what's a 529 versus a custodial account", "529 vs Custodial"),
    ("how do I debug nftables counters", "nftables Counter Debug"),
    ("workers analytics engine vs logs", "Analytics Engine vs Logs"),
    ("how do I add device code flow", "OAuth Device Code"),
    ("what's a verifier model", "Verifier Model Basics"),
    ("how do I eval exact match vs valid label rate", "Label Eval Metrics"),
    ("github copilot workspace vs local agents", "Copilot vs Local Agents"),
    ("my nvme thermals throttle under rustc", "NVMe Thermal Throttle"),
    ("how do I get a refundable fare without paying 3x", "Refundable Fare Options"),
    ("how do I keep ginger from going woody", "Ginger Storage"),
    ("what's a good default collection period", "AR Collection Period"),
    ("how do I use perf to find a hot function", "perf Hot Function"),
    ("nuxt prerender vs ssr on workers", "Nuxt Prerender vs SSR"),
    ("how do I add step up auth for risky actions", "Step Up Authentication"),
    ("what's a process reward model", "Process Reward Model"),
    ("how do I avoid catastrophic forgetting in sft", "SFT Catastrophic Forgetting"),
    ("the chassis buzzes at certain fan rpm", "Chassis Fan Buzz"),
    ("how do I pick a travel credit card", "Travel Credit Card"),
    ("how do I make a vinaigrette that emulsifies", "Vinaigrette Emulsion"),
    ("what's a good default dso for saas", "SaaS DSO Target"),
    ("how do I enable psi memory pressure logs", "Linux PSI Memory"),
    ("cloudflare spectrum vs a tunnel for tcp", "Spectrum vs Tunnel"),
    ("how do I design a kill switch for a feature", "Feature Kill Switch"),
    ("what's quantization aware training", "Quantization Aware Training"),
    ("how do I mix old labeling data into a new task", "Mix Replay Data"),
    ("github merge conflict in a lockfile", "Lockfile Merge Conflict"),
    ("my webcam autofocus hunts in a call", "Webcam Autofocus Hunt"),
    ("how do I get a visa on arrival", "Visa On Arrival"),
    ("how do I keep parsley from turning slime", "Parsley Storage"),
    ("what's a good default contribution margin", "Contribution Margin Target"),
    ("how do I use eBPF to trace syscalls", "eBPF Syscall Trace"),
    ("workers smart placement vs a single region", "Smart Placement Regions"),
    ("how do I add ip allowlists for admin", "Admin IP Allowlist"),
    ("what's lora rank and alpha", "LoRA Rank and Alpha"),
    ("how do I raise num predict for longer bros tasks", "Bros Longer Outputs"),
    ("the power brick smells like hot plastic", "Laptop Charger Smell"),
    ("how do I choose between a rail pass and point to point", "Rail Pass vs Tickets"),
    ("how do I make a pan sauce after a steak", "Steak Pan Sauce"),
    ("what's a good default ltv to cac", "LTV to CAC"),
    ("how do I enable io_uring for nginx", "nginx IO Uring"),
    ("cloudflare d1 time travel restore", "D1 Time Travel"),
    ("how do I add just in time admin", "JIT Admin Access"),
    ("what's qlora and do I need it for 135m", "QLoRA for Small Models"),
    ("how do I keep bros under 100mb", "Bros Model Size"),
    ("github required reviewers from code owners", "CODEOWNERS Reviewers"),
    ("my sd card is read only suddenly", "SD Card Read Only"),
    ("how do I get a global entry interview", "Global Entry Interview"),
    ("how do I keep a cast iron skillet seasoned", "Cast Iron Seasoning"),
    ("what's a good default magic number for nrr", "Net Revenue Retention"),
    ("how do I use ss to find a listening port", "ss Listening Ports"),
    ("workers pipelines vs queues", "Pipelines vs Queues"),
    ("how do I add customer managed keys", "Customer Managed Keys"),
    ("what's a chat template and why does it matter", "Chat Template Basics"),
    ("how do I call bros with a Label tag", "Bros Label Tag"),
    ("the laptop won't charge past 80 after a firmware thing", "Charge Limit Firmware"),
    ("how do I pick a hostel vs a hotel for one night", "Hostel vs Hotel"),
    ("how do I make a simple dashi", "Simple Dashi"),
    ("what's a good default payback period", "CAC Payback Period"),
    ("how do I use lsof on a deleted but open file", "lsof Deleted Files"),
    ("cloudflare vectorize vs an external vector db", "Vectorize vs External DB"),
    ("how do I add a data processing addendum", "DPA Addendum"),
    ("what's supervised fine tuning in one sentence", "SFT One Sentence"),
    ("how do I reinstall bros after a retrain", "Reinstall Bros Model"),
    ("github autolink to linear tickets", "GitHub Linear Autolink"),
    ("my microsd adapter is flaky in a camera", "MicroSD Adapter Flake"),
    ("how do I get a seat together as a family", "Family Seat Assignment"),
    ("how do I keep a baguette overnight", "Overnight Baguette"),
    ("what's a good default rule of 40", "Rule of 40"),
    ("how do I use tmux for a long train job", "tmux Training Job"),
    ("workers secrets store vs vars", "Secrets vs Vars"),
    ("how do I add a subprocessors list", "Subprocessors List"),
    ("what's peft in one sentence", "PEFT One Sentence"),
    ("how do I add examples without duplicating prompts", "Avoid Duplicate Prompts"),
    ("the bios virtualization toggle is greyed out", "BIOS Virtualization Grey"),
    ("how do I pick travel insurance for a long trip", "Travel Insurance Pick"),
    ("how do I make a simple aioli", "Simple Aioli"),
    ("what's a good default gross margin for saas", "SaaS Gross Margin"),
    ("how do I use ionice for a backup job", "ionice Backup Job"),
    ("cloudflare email routing vs a mailbox host", "Email Routing vs Host"),
    ("how do I add a dsr workflow for gdpr", "GDPR Data Subject Request"),
    ("what's a tokenizer special token", "Special Tokens"),
    ("how do I keep train val test from leaking", "Prevent Split Leakage"),
    ("github deploy keys vs a machine user", "Deploy Keys vs Machine User"),
    ("my usb c cable only charges not data", "USB Charge Only Cable"),
    ("how do I get a visa photo background right", "Visa Photo Background"),
    ("how do I keep olive oil from going rancid", "Olive Oil Storage"),
    ("what's a good default expansion mrr mix", "Expansion MRR Mix"),
    ("how do I use nice and taskset together", "nice and taskset"),
    ("workers vpc vs a tunnel to origin", "VPC vs Origin Tunnel"),
    ("how do I add retention labels to tickets", "Ticket Retention Labels"),
    ("what's teacher forcing in sft", "Teacher Forcing"),
    ("how do I shuffle with a fixed seed", "Deterministic Data Shuffle"),
    ("the laptop fingerprint reader vanished after an update", "Fingerprint Reader Missing"),
    ("how do I get a visa for a multi country trip", "Multi Country Visa"),
    ("how do I keep honey from crystallizing badly", "Honey Crystallization"),
    ("what's a good default logo retention", "Logo Retention Target"),
    ("how do I use systemd-run for a one shot", "systemd run One Shot"),
    ("cloudflare load balancing vs dns failover", "Load Balancing vs DNS"),
    ("how do I add a security.txt", "Security Text File"),
    ("what's packed sft versus unpacked", "Packed vs Unpacked SFT"),
    ("how do I document a new bros skill", "Document Bros Skill"),
    ("github large file blocked at 100mb", "GitHub 100MB Limit"),
    ("my sd card speed is fake cheap garbage", "Fake SD Card Speed"),
    ("how do I get lounge access without status", "Lounge Access Without Status"),
    ("how do I keep garlic from sprouting", "Garlic Sprouting"),
    ("what's a good default net dollar retention", "Net Dollar Retention"),
    ("how do I use coredumpctl after a crash", "coredumpctl After Crash"),
    ("cloudflare browser rendering vs playwright", "Browser Rendering vs Playwright"),
    ("how do I add a responsible disclosure page", "Responsible Disclosure Page"),
    ("what's left padding in a causal lm", "Causal LM Padding"),
    ("how do I keep the ollama name bros after new skills", "Keep Bros Model Name"),
    ("the bios boot order ignores my usb", "BIOS USB Boot Order"),
    ("how do I pick a visa-free route", "Visa Free Route"),
    ("how do I keep a cut avocado green till lunch", "Cut Avocado Lunch"),
    ("what's a good default magic number for churn", "Logo Churn Target"),
    ("how do I use nsenter into a container", "nsenter Container"),
    ("cloudflare snippets vs a worker", "Snippets vs Worker"),
    ("how do I add a bug bounty later", "Start Bug Bounty"),
    ("what's an eos token in generation", "EOS Token Generation"),
    ("how do I smoke test training on one step", "One Step Smoke Train"),
    ("github lfs vs just staying under 100mb", "Git LFS vs Small Files"),
    ("my webcam needs extra lighting that looks awful", "Webcam Lighting"),
    ("how do I get a visa invitation letter", "Visa Invitation Letter"),
    ("how do I keep cooked rice from drying out", "Cooked Rice Storage"),
    ("what's a good default paid cac", "Paid CAC Target"),
    ("how do I use capsh to debug capabilities", "capsh Capabilities"),
    ("cloudflare ai gateway vs calling a provider", "AI Gateway vs Direct"),
    ("how do I add a status twitter without the chaos", "Incident Status Channel"),
    ("what's temperature 0 good for", "Zero Temperature Decoding"),
    ("how do I keep bros replies to a label only", "Label Only Replies"),
    ("the laptop mic is picking up the fans", "Mic Fan Noise"),
    ("how do I pick a visa run strategy", "Visa Run Strategy"),
    ("how do I keep herbs from the store alive a week", "Store Herb Longevity"),
    ("what's a good default organic cac", "Organic CAC Target"),
    ("how do I use lsns to see namespaces", "lsns Namespaces"),
    ("cloudflare constellation vs workers ai", "Constellation vs Workers AI"),
    ("how do I add a customer advisory board", "Customer Advisory Board"),
    ("what's top k versus top p", "Top K vs Top P"),
    ("how do I stop bros from explaining the label", "No Label Explanations"),
    ("github submodule for a model repo", "Git Submodule Model Repo"),
    ("my webcam privacy shutter is stuck", "Webcam Shutter Stuck"),
    ("how do I get a visa appointment in a third country", "Third Country Visa"),
    ("how do I keep leftover pizza edible next day", "Leftover Pizza"),
    ("what's a good default sales cycle length", "Sales Cycle Length"),
    ("how do I use findmnt to see bind mounts", "findmnt Bind Mounts"),
    ("cloudflare pubsub vs a queue", "PubSub vs Queue"),
    ("how do I add a changelog customers read", "Customer Changelog"),
    ("what's greedy decoding", "Greedy Decoding"),
    ("how do I install bros with OLLAMA_HOST set", "Bros OLLAMA HOST"),
    ("the laptop speakers rattle at one frequency", "Speaker Rattle"),
    ("how do I pick a visa photo size", "Visa Photo Size"),
    ("how do I keep leftover pasta from welding together", "Leftover Pasta"),
    ("what's a good default win rate", "Sales Win Rate"),
    ("how do I use numactl on a two socket box", "numactl Two Socket"),
    ("cloudflare queues consumer retries", "Queue Consumer Retries"),
    ("how do I add a public roadmap without overpromising", "Public Roadmap"),
    ("what's a stop sequence in ollama", "Ollama Stop Sequence"),
    ("how do I point the modelfile at the gguf", "Modelfile GGUF Path"),
    ("github clone depth 1 for the model", "Shallow Clone Model"),
    ("my webcam is huge in preview and tiny in the call", "Webcam Preview Size"),
    ("how do I get a visa for a conference last minute", "Last Minute Conference Visa"),
    ("how do I keep leftover soup safe three days", "Leftover Soup Safety"),
    ("what's a good default demo to close rate", "Demo to Close"),
    ("how do I use chrt for a latency sensitive job", "chrt Latency Job"),
    ("cloudflare durable object alarms", "Durable Object Alarms"),
    ("how do I add a kill fee in a contract", "Contract Kill Fee"),
    ("what's num predict in ollama", "Ollama Token Limit"),
    ("how do I fail install-ollama if the gguf is missing", "Missing GGUF Install Fail"),
    ("the laptop camera light stays on", "Camera Light Stays On"),
    ("how do I pick a visa for a cruise port", "Cruise Port Visa"),
    ("how do I keep leftover fish from smelling the fridge", "Leftover Fish Smell"),
    ("what's a good default expansion rate", "Expansion Rate Target"),
    ("how do I use taskset to pin training to p cores", "Pin Training Cores"),
    ("cloudflare websocket hibernation", "WebSocket Hibernation"),
    ("how do I add a most favored nation clause", "MFN Contract Clause"),
    ("what's a modelfile SYSTEM instruction", "Modelfile SYSTEM"),
    ("how do I keep install-ollama noninteractive", "Noninteractive Ollama Create"),
    ("github submodule update init recursive", "Submodule Update Init"),
    ("my webcam looks 240p on linux", "Linux Webcam Resolution"),
    ("how do I pick a visa for a land border", "Land Border Visa"),
    ("how do I keep leftover garlic bread from going leathery", "Leftover Garlic Bread"),
    ("what's a good default logo churn monthly", "Monthly Logo Churn"),
    ("how do I use cpupower frequency-info", "cpupower Frequency Info"),
    ("cloudflare d1 batch statements", "D1 Batch Statements"),
    ("how do I add a change of control clause", "Change of Control Clause"),
    ("what's a chatml im start token", "ChatML Start Token"),
    ("how do I keep the packaged gguf in models", "Commit Packaged GGUF"),
    ("the laptop lid sensor thinks it's closed", "Lid Sensor False Close"),
    ("how do I pick a visa for a ferry", "Ferry Visa"),
    ("how do I keep leftover pancakes from getting sad", "Leftover Pancakes"),
    ("what's a good default net retention quarterly", "Quarterly Net Retention"),
    ("how do I use turbostat during a compile", "turbostat During Compile"),
    ("cloudflare r2 multipart upload", "R2 Multipart Upload"),
    ("how do I add a source code escrow", "Source Code Escrow"),
    ("what's an im end stop token", "ChatML End Token"),
    ("how do I ignore training adapters in git", "Gitignore Training Output"),
    ("github keep source jsonl in git", "Commit Source JSONL"),
    ("my webcam has a rolling tear on wayland", "Wayland Webcam Tear"),
    ("how do I pick a visa for a road trip", "Road Trip Visa"),
    ("how do I keep leftover waffles crisp", "Leftover Waffle Crisp"),
    ("what's a good default magic number for nps", "NPS Target"),
    ("how do I use powertop without wrecking usb", "powertop USB Caution"),
    ("cloudflare kv eventual consistency gotcha", "KV Eventual Consistency"),
    ("how do I add a data residency option", "Data Residency Option"),
    ("what's apply chat template", "Apply Chat Template"),
    ("how do I add a Label prefix in training data", "Training Label Prefix"),
    ("the laptop charges slow on a third party brick", "Third Party Charger Slow"),
    ("how do I pick a visa for a train through a third country", "Train Third Country Visa"),
    ("how do I keep leftover dumplings from sticking", "Leftover Dumplings"),
    ("what's a good default csat", "CSAT Target"),
    ("how do I use undervolt safely on a 3080 laptop", "Laptop Undervolt"),
    ("cloudflare durable object storage limits", "Durable Object Storage"),
    ("how do I add a subprocessors change notice", "Subprocessor Change Notice"),
    ("what's completion only loss", "Completion Only Loss"),
    ("how do I train bros on conversational prompt completion", "Conversational SFT Format"),
    ("github do not commit f16 gguf", "Ignore FP16 GGUF"),
    ("my webcam autoexposure blows out a window", "Webcam Autoexposure"),
    ("how do I pick a visa for a workation", "Workation Visa"),
    ("how do I keep leftover fries from going limp", "Leftover Fries"),
    ("what's a good default time to first value", "Time to First Value"),
    ("how do I use nvidia-smi during training", "nvidia smi During Training"),
    ("cloudflare d1 foreign keys", "D1 Foreign Keys"),
    ("how do I add a data processing record", "ROPAs Record"),
    ("what's max length in sft config", "SFT Max Length"),
    ("how do I keep packing off for short labels", "SFT Packing Off"),
    ("the laptop gpu is in a sleep state and training fails", "GPU Sleep Training Fail"),
    ("how do I pick a visa for remote work", "Remote Work Visa"),
    ("how do I keep leftover nachos from a disaster", "Leftover Nachos"),
    ("what's a good default activation rate", "Activation Rate Target"),
    ("how do I use CUDA_VISIBLE_DEVICES for one gpu", "CUDA Visible Devices"),
    ("cloudflare workers cpu time limits", "Workers CPU Limits"),
    ("how do I add a privacy policy people can read", "Readable Privacy Policy"),
    ("what's lora dropout", "LoRA Dropout"),
    ("how do I target q proj and mlp modules", "LoRA Target Modules"),
    ("github install from a submodule path", "Submodule Install Path"),
    ("my webcam ir blaster confuses face unlock", "IR Face Unlock"),
    ("how do I pick a visa for a digital nomad", "Digital Nomad Visa"),
    ("how do I keep leftover sushi for lunch tomorrow", "Leftover Sushi"),
    ("what's a good default trial conversion", "Trial Conversion Rate"),
    ("how do I use bf16 on ampere", "Ampere bf16 Training"),
    ("cloudflare workers memory limits", "Workers Memory Limits"),
    ("how do I add cookie consent without a dark pattern", "Honest Cookie Consent"),
    ("what's peft task type causal lm", "PEFT Causal LM"),
    ("how do I save tokenizer with the adapter", "Save Adapter Tokenizer"),
    ("the laptop mux switch is stuck on igpu", "Mux Switch iGPU"),
    ("how do I pick a visa for a film festival", "Film Festival Visa"),
    ("how do I keep leftover tacos from a soggy mess", "Leftover Tacos"),
    ("what's a good default free to paid", "Free to Paid Rate"),
    ("how do I fall back to fp16 if no bf16", "fp16 Fallback"),
    ("cloudflare workers subrequest limits", "Workers Subrequest Limits"),
    ("how do I add a dpa without a law firm novel", "Simple DPA"),
    ("what's merge and unload", "Merge And Unload"),
    ("how do I merge then convert to gguf", "Merge Then GGUF"),
    ("github honor OLLAMA_HOST in the app", "Honor Ollama Host"),
    ("my webcam privacy led is too bright at night", "Privacy LED Bright"),
    ("how do I pick a visa for a sports event", "Sports Event Visa"),
    ("how do I keep leftover burgers from drying", "Leftover Burgers"),
    ("what's a good default paid conversion", "Paid Conversion Rate"),
    ("how do I train on cpu if cuda is missing", "CPU Training Fallback"),
    ("cloudflare workers isolate model", "Workers Isolate Model"),
    ("how do I add a terms of service that isn't 40 pages", "Short Terms of Service"),
    ("what's safe serialization for merged weights", "Safe Serialization"),
    ("how do I copy q4 into models after quantize", "Copy Q4 to models"),
    ("the laptop egpu is flaky on thunderbolt", "eGPU Thunderbolt Flake"),
    ("how do I pick a visa for a volunteer trip", "Volunteer Trip Visa"),
    ("how do I keep leftover curry overnight", "Leftover Curry"),
    ("what's a good default nrr including expansion", "NRR With Expansion"),
    ("how do I set a seed for reproducible sft", "Reproducible SFT Seed"),
    ("cloudflare workers compatibility date", "Workers Compat Date"),
    ("how do I add an acceptable use policy", "Acceptable Use Policy"),
    ("what's llama quantize q4 k m", "llama quantize Q4"),
    ("how do I fall back to q4 0 under 100mb", "Q4 Size Fallback"),
    ("github do not vendor llama cpp", "Do Not Vendor llamacpp"),
    ("my webcam needs v4l2loopback for virtual cams", "v4l2loopback Virtual Cam"),
    ("how do I pick a visa for a pilgrimage", "Pilgrimage Visa"),
    ("how do I keep leftover stew for two days", "Leftover Stew"),
    ("what's a good default grr", "Gross Revenue Retention"),
    ("how do I log eval exact match honestly", "Honest Exact Match"),
    ("cloudflare workers node compat", "Workers Node Compat"),
    ("how do I add a subprocessors exhibit", "Subprocessors Exhibit"),
    ("what's convert hf to gguf py", "Convert HF to GGUF"),
    ("how do I pass llama cpp path to convert", "Convert Script Argument"),
    ("the laptop iGPU drives the laptop screen only", "iGPU Internal Display"),
    ("how do I pick a visa for a language school", "Language School Visa"),
    ("how do I keep leftover risotto from turning glue", "Leftover Risotto"),
    ("what's a good default logo expansion", "Logo Expansion Rate"),
    ("how do I print prompt expected predicted", "Eval Print Format"),
    ("cloudflare workers python vs js", "Workers Python vs JS"),
    ("how do I add a data map of systems", "Systems Data Map"),
    ("what's an ollama create from a modelfile", "ollama create Modelfile"),
    ("how do I run bros after install", "ollama run bros"),
    ("github submodule add vendor bros", "Submodule Add Vendor Bros"),
    ("my webcam ir is disabled in the bios", "BIOS IR Camera"),
    ("how do I pick a visa for a research visit", "Research Visit Visa"),
    ("how do I keep leftover noodles from a brick", "Leftover Noodles"),
    ("what's a good default seat expansion", "Seat Expansion Rate"),
    ("how do I compute average generated label length", "Average Label Length"),
    ("cloudflare workers cron secrets", "Workers Cron Secrets"),
    ("how do I add a records of processing", "Records of Processing"),
    ("what's a local ollama api for the bros app", "Local Ollama API"),
    ("how do I send Label plus the first user message", "App Label Prompt"),
    ("the laptop dgpu only works on the hdmi port", "dGPU HDMI Only"),
    ("how do I pick a visa for an artist residency", "Artist Residency Visa"),
    ("how do I keep leftover bread from staling fast", "Leftover Bread"),
    ("what's a good default usage expansion", "Usage Expansion Rate"),
    ("how do I treat exact match as a weak metric", "Weak Exact Match"),
    ("cloudflare workers observability logs", "Workers Observability"),
    ("how do I add a lawful basis table", "Lawful Basis Table"),
    ("what's production runtime for bros", "Bros Production Runtime"),
    ("how do I keep python out of the bros app runtime", "Training Time Python Only"),
    ("github keep models gguf tracked", "Track models GGUF"),
    ("my webcam shutter sound is a legal thing in this country", "Webcam Shutter Law"),
    ("how do I pick a visa for a medical trip", "Medical Trip Visa"),
    ("how do I keep leftover salad from wilting", "Leftover Salad"),
    ("what's a good default contraction mrr", "Contraction MRR"),
    ("how do I validate labels have no punctuation", "Label Punctuation Check"),
    ("cloudflare workers tail logs", "Workers Tail Logs"),
    ("how do I add a transfer impact assessment", "Transfer Impact Assessment"),
    ("what's a 135m instruct checkpoint", "SmolLM2 Instruct 135M"),
    ("how do I not swap in a larger base model", "Keep 135M Base"),
    ("the laptop nvidia driver failed after a kernel update", "NVIDIA Driver After Kernel"),
    ("how do I pick a visa for a family reunion", "Family Reunion Visa"),
    ("how do I keep leftover fruit from attracting fruit flies", "Fruit Fly Leftovers"),
    ("what's a good default reactivation rate", "Reactivation Rate"),
    ("how do I reject duplicate prompts in prepare data", "Duplicate Prompt Reject"),
    ("cloudflare workers secrets rotate", "Workers Secret Rotate"),
    ("how do I add a scc module", "Standard Contractual Clauses"),
    ("what's huggingface tb smollm2", "HuggingFaceTB SmolLM2"),
    ("how do I load jsonl with datasets", "Load JSONL Dataset"),
    ("github 80 10 10 split seed 42", "Deterministic 80 10 10"),
    ("my webcam needs extra power from the dock", "Webcam Dock Power"),
    ("how do I pick a visa for an adoption trip", "Adoption Trip Visa"),
    ("how do I keep leftover cheese from molding", "Leftover Cheese"),
    ("what's a good default referral rate", "Referral Rate Target"),
    ("how do I require Label tag on label tasks", "Require Label Tag"),
    ("cloudflare workers wrangler whoami", "wrangler whoami"),
    ("how do I add a cookie inventory", "Cookie Inventory"),
    ("what's trl sft trainer", "TRL SFTTrainer"),
    ("how do I pass peft config into sft trainer", "SFT Trainer PEFT Config"),
    ("the laptop external monitor flickers on usb c", "USBC Monitor Flicker"),
    ("how do I pick a visa for a sports tournament", "Sports Tournament Visa"),
    ("how do I keep leftover herbs in a jar of water", "Herbs In Water"),
    ("what's a good default virality coefficient", "Virality Coefficient"),
    ("how do I allow longer completions for non label tasks", "Non Label Completions"),
    ("cloudflare workers local dev", "Workers Local Dev"),
    ("how do I add a retention schedule", "Data Retention Schedule"),
    ("what's lora r 16 alpha 32", "LoRA r16 alpha32"),
    ("how do I eval on the validation split each epoch", "Epoch Validation Eval"),
    ("github first skill is chat labeling", "First Skill Labeling"),
    ("my webcam autofocus hunts on a plain wall", "Autofocus Plain Wall"),
    ("how do I pick a visa for a university visit", "University Visit Visa"),
    ("how do I keep leftover soup from exploding in the microwave", "Microwave Soup Cover"),
    ("what's a good default k factor", "K Factor Target"),
    ("how do I add a task field to jsonl", "JSONL task Field"),
    ("cloudflare workers minify", "Workers Minify"),
    ("how do I add a deletion pipeline", "Data Deletion Pipeline"),
    ("what's gradient accumulation 2", "Gradient Accumulation 2"),
    ("how do I use batch size 8 on a 3080", "Batch Size 8"),
    ("the laptop 3080 is plenty for 135m lora", "3080 Enough For 135M"),
    ("how do I pick a visa for a language exam", "Language Exam Visa"),
    ("how do I keep leftover sauce from skinning", "Leftover Sauce Skin"),
    ("what's a good default magic number for dau mau", "DAU MAU Ratio"),
    ("how do I keep later skills on the same ollama name", "Same Ollama Name"),
    ("cloudflare workers source maps", "Workers Source Maps"),
    ("how do I add a backup restore test", "Backup Restore Test"),
    ("what's learning rate 2e-4 for lora", "LoRA Learning Rate"),
    ("how do I train three epochs on a thousand examples", "Three Epochs Thousand"),
    ("github replay labeling data when adding skills", "Replay Labeling Data"),
    ("my webcam needs a dummy plug for headless", "Headless Dummy Plug"),
    ("how do I pick a visa for a choir tour", "Choir Tour Visa"),
    ("how do I keep leftover gravy from a lump", "Leftover Gravy"),
    ("what's a good default stickiness", "Product Stickiness"),
    ("how do I merge after each training stage", "Merge Each Stage"),
    ("cloudflare workers cpu profiling", "Workers CPU Profiling"),
    ("how do I add an incident comms template", "Incident Comms Template"),
    ("what's max new tokens 16", "Max New Tokens"),
    ("how do I generate without sampling", "Disable Sampling"),
    ("the laptop 16gb vram dwarfs a 135m adapter", "16GB vs 135M"),
    ("how do I pick a visa for a teaching gig", "Teaching Gig Visa"),
    ("how do I keep leftover mashed potatoes decent", "Leftover Mashed Potatoes"),
    ("what's a good default session length", "Session Length Target"),
    ("how do I not invent extra tasks in v1", "No Extra v1 Tasks"),
    ("cloudflare workers flamegraph", "Workers Flamegraph"),
    ("how do I add a severity rubric", "Incident Severity Rubric"),
    ("what's pad token equals eos", "Pad Token EOS"),
    ("how do I skip special tokens on decode", "Skip Special Tokens"),
    ("github v1 dataset is labels only", "v1 Labels Only"),
    ("my webcam needs udev rules on linux", "Webcam udev Rules"),
    ("how do I pick a visa for a research conference", "Research Conference Visa"),
    ("how do I keep leftover gravy from a fridge skin", "Fridge Gravy Skin"),
    ("what's a good default pages per session", "Pages Per Session"),
    ("how do I document continued training in the readme", "README Continued Training"),
    ("cloudflare workers cpu accounting", "Workers CPU Accounting"),
    ("how do I add a blameless timeline", "Blameless Timeline"),
    ("what's device map auto on cuda", "Device Map Auto"),
    ("how do I avoid device map on cpu trainer issues", "CPU Skip Device Map"),
    ("the laptop cuda is available for bros training", "CUDA Available Training"),
    ("how do I pick a visa for an unpaid internship", "Unpaid Internship Visa"),
    ("how do I keep leftover casserole from drying", "Leftover Casserole"),
    ("what's a good default bounce rate", "Bounce Rate Target"),
    ("how do I keep the starter set varied", "Varied Starter Set"),
    ("cloudflare workers request limits", "Workers Request Limits"),
    ("how do I add a customer incident mail", "Customer Incident Mail"),
    ("what's report to none", "Disable Report To"),
    ("how do I disable wandb during sft", "Disable WandB"),
    ("github seed 42 everywhere", "Seed 42 Everywhere"),
    ("my webcam needs cheese for a still", "cheese Webcam Still"),
    ("how do I pick a visa for a working holiday", "Working Holiday Visa"),
    ("how do I keep leftover lasagna overnight", "Leftover Lasagna"),
    ("what's a good default activation time", "Activation Time Target"),
    ("how do I cover programming and travel in one dataset", "Broad Domain Coverage"),
    ("cloudflare workers subrequest loops", "Workers Subrequest Loops"),
    ("how do I add a status page subscriber list", "Status Page Subscribers"),
    ("what's logging steps 10", "Logging Steps Ten"),
    ("how do I save on epoch not every step", "Save Strategy Epoch"),
    ("the laptop driver is 580 so cuda torch should work", "Driver 580 CUDA Torch"),
    ("how do I pick a visa for a spouse join", "Spouse Join Visa"),
    ("how do I keep leftover enchiladas from a soggy tortilla", "Leftover Enchiladas"),
    ("what's a good default time to close", "Time to Close"),
    ("how do I include typos in the training prompts", "Typos In Prompts"),
    ("cloudflare workers cpu timeout", "Workers CPU Timeout"),
    ("how do I add a war room channel", "War Room Channel"),
    ("what's eval strategy epoch", "Eval Strategy Epoch"),
    ("how do I switch eval to steps for a smoke train", "Smoke Train Eval Steps"),
    ("github max steps 1 for a smoke test", "Smoke Test Max Steps"),
    ("my webcam needs guvcview on linux", "guvcview Linux"),
    ("how do I pick a visa for a parent visit", "Parent Visit Visa"),
    ("how do I keep leftover biryani from drying", "Leftover Biryani"),
    ("what's a good default pipeline coverage", "Pipeline Coverage"),
    ("how do I include long rambling user prompts", "Long User Prompts"),
    ("cloudflare workers wall clock", "Workers Wall Clock"),
    ("how do I add a customer apology template", "Customer Apology Template"),
    ("what's gradient checkpointing", "Gradient Checkpointing"),
    ("how do I set use reentrant false", "Checkpointing Non Reentrant"),
    ("the laptop 62gb ram is fine for 135m", "62GB RAM Enough"),
    ("how do I pick a visa for a child visit", "Child Visit Visa"),
    ("how do I keep leftover tikka from drying", "Leftover Tikka"),
    ("what's a good default sql to opp", "SQL to Opportunity"),
    ("how do I include short two word user prompts", "Short User Prompts"),
    ("cloudflare workers isolate recycle", "Workers Isolate Recycle"),
    ("how do I add a post incident review invite", "PIR Invite"),
    ("what's processing class tokenizer", "Processing Class Tokenizer"),
    ("how do I not pass the old tokenizer kwarg", "No Old tokenizer Kwarg"),
    ("github current trl sft apis", "Current TRL APIs"),
    ("my webcam needs v4l2-ctl formats", "v4l2 ctl Formats"),
    ("how do I pick a visa for a business meeting", "Business Meeting Visa"),
    ("how do I keep leftover naan soft", "Leftover Naan"),
    ("what's a good default opp to close", "Opportunity to Close"),
    ("how do I include implicit intent prompts", "Implicit Intent Prompts"),
    ("cloudflare workers colo routing", "Workers Colo Routing"),
    ("how do I add a customer credit after an incident", "Incident Customer Credit"),
    ("what's model init kwargs dtype", "Model Init Dtype"),
    ("how do I avoid torch dtype deprecated", "Avoid Deprecated Dtype"),
    ("the laptop is ampere so bf16 is supported", "Ampere bf16 Supported"),
    ("how do I pick a visa for a product launch trip", "Product Launch Trip Visa"),
    ("how do I keep leftover hummus a week", "Leftover Hummus"),
    ("what's a good default inbound vs outbound mix", "Inbound vs Outbound"),
    ("how do I include multi concept prompts", "Multi Concept Prompts"),
    ("cloudflare workers cache api", "Workers Cache API"),
    ("how do I add a customer sla credit math", "SLA Credit Math"),
    ("what's task type causal lm", "Causal LM Task"),
    ("how do I set bias none on lora", "LoRA bias none"),
    ("github no qlora for 135m", "No QLoRA Needed"),
    ("my webcam needs cheese -f jpeg", "cheese JPEG Capture"),
    ("how do I pick a visa for a factory visit", "Factory Visit Visa"),
    ("how do I keep leftover baba ganoush", "Leftover Baba Ganoush"),
    ("what's a good default sales accepted lead rate", "SAL Rate"),
    ("how do I include casual wording in prompts", "Casual Prompt Wording"),
    ("cloudflare workers caches default", "Workers Default Cache"),
    ("how do I add a customer status emoji policy", "Status Emoji Policy"),
    ("what's output dir adapter", "Adapter Output Directory"),
    ("how do I save merged under output merged", "Merged Output Directory"),
    ("the packaged artifact is models bros q4", "Packaged Bros GGUF"),
    ("how do I pick a visa for a supplier visit", "Supplier Visit Visa"),
    ("how do I keep leftover tzatziki", "Leftover Tzatziki"),
    ("what's a good default mql to sql", "MQL to SQL"),
    ("how do I include troubleshooting prompts", "Troubleshooting Prompts"),
    ("cloudflare workers waitUntil", "Workers waitUntil"),
    ("how do I add a customer maintenance window mail", "Maintenance Window Mail"),
    ("what's ollama model name bros", "Ollama Name Bros"),
    ("how do I keep the consuming app name bros", "Bros App Name"),
    ("github this repo does not implement the app", "Repo Not The App"),
    ("my webcam needs mpv av://v4l2", "mpv V4L2 Preview"),
    ("how do I pick a visa for a board meeting", "Board Meeting Visa"),
    ("how do I keep leftover guacamole green", "Leftover Guacamole"),
    ("what's a good default sql acceptance", "SQL Acceptance Rate"),
    ("how do I include hardware prompts", "Hardware Prompts"),
    ("cloudflare workers passThroughOnException", "Pass Through On Exception"),
    ("how do I add a customer sunset notice", "Product Sunset Notice"),
    ("what's first user message labeling", "First Message Label"),
    ("how do I extract subject from a messy prompt", "Extract Main Subject"),
    ("the model is not a general chatbot", "Not A Chatbot"),
    ("how do I pick a visa for a trade show", "Trade Show Visa"),
    ("how do I keep leftover salsa from separating", "Leftover Salsa"),
    ("what's a good default demo show rate", "Demo Show Rate"),
    ("how do I include finance prompts", "Finance Prompts"),
    ("cloudflare workers scheduled handler", "Workers Scheduled Handler"),
    ("how do I add a customer migration guide", "Customer Migration Guide"),
    ("what's a concise title like label", "Title Like Label"),
    ("how do I avoid markdown in labels", "No Markdown Labels"),
    ("github no punctuation in labels", "No Punctuation Labels"),
    ("my webcam needs ffmpeg v4l2", "ffmpeg V4L2 Capture"),
    ("how do I pick a visa for a hackathon", "Hackathon Visa"),
    ("how do I keep leftover pesto from browning", "Leftover Pesto"),
    ("what's a good default no show rate", "No Show Rate"),
    ("how do I include shopping prompts", "Shopping Prompts"),
    ("cloudflare workers email handler", "Workers Email Handler"),
    ("how do I add a customer deprecation timeline", "Deprecation Timeline"),
    ("what's return only the label", "Return Only Label"),
    ("how do I avoid here is your label", "No Here Is Your Label"),
    ("the tiny model prioritizes format over chat skill", "Format Over Chat"),
    ("how do I pick a visa for an open source summit", "Open Source Summit Visa"),
    ("how do I keep leftover chimichurri", "Leftover Chimichurri"),
    ("what's a good default cycle time", "Sales Cycle Time"),
    ("how do I include everyday questions", "Everyday Questions"),
    ("cloudflare workers tcp sockets", "Workers TCP Sockets"),
    ("how do I add a customer export tool", "Customer Data Export"),
    ("what's 2 to 5 word labels", "Two To Five Words"),
    ("how do I keep labels descriptive not cute", "Descriptive Not Cute"),
    ("github vary grammar and length", "Vary Grammar Length"),
    ("my webcam needs cheese countdown", "cheese Countdown"),
    ("how do I pick a visa for a user conference", "User Conference Visa"),
    ("how do I keep leftover tahini from separating", "Leftover Tahini"),
    ("what's a good default expansion attach", "Expansion Attach Rate"),
    ("how do I include linux prompts", "Linux Prompts"),
    ("cloudflare workers connect", "Workers TCP Connect"),
    ("how do I add a customer import mapping", "Customer Import Mapping"),
    ("what's docker networking as a sample label", "Sample Docker Networking"),
    ("how do I label a postgres connection issue", "Sample Postgres Issue"),
    ("the sample nuxt cloudflare deploy label", "Sample Nuxt Cloudflare"),
    ("how do I pick a visa for a partner summit", "Partner Summit Visa"),
    ("how do I keep leftover peanut sauce", "Leftover Peanut Sauce"),
    ("what's a good default seat attach", "Seat Attach Rate"),
    ("how do I include kubernetes prompts", "Kubernetes Prompts"),
    ("cloudflare workers streams", "Workers Streams"),
    ("how do I add a customer sandbox reset", "Customer Sandbox Reset"),
    ("what's agents vs models as a sample", "Sample Agents vs Models"),
    ("how do I label llm fine tuning", "Sample LLM Fine Tuning"),
    ("github include mcp prompts", "MCP Prompts"),
    ("my webcam needs v4l2loopback chrome", "Chrome Virtual Cam"),
    ("how do I pick a visa for a customer visit", "Customer Visit Visa"),
    ("how do I keep leftover soy sauce dishes overnight", "Leftover Soy Dishes"),
    ("what's a good default product qualified lead", "PQL Target"),
    ("how do I include saas prompts", "SaaS Prompts"),
    ("cloudflare workers transform streams", "Transform Streams"),
    ("how do I add a customer impersonation audit", "Impersonation Audit"),
    ("what's cloudflare docker setup as a sample", "Sample Cloudflare Docker"),
    ("how do I label a git rebase question", "Sample Git Rebase"),
    ("the dataset must not repeat the same prompt", "No Repeated Prompts"),
    ("how do I pick a visa for an investor meeting", "Investor Meeting Visa"),
    ("how do I keep leftover coconut milk curry", "Leftover Coconut Curry"),
    ("what's a good default sales qualified opportunity", "SQO Target"),
    ("how do I include architecture prompts", "Architecture Prompts"),
    ("cloudflare workers readable streams", "Readable Streams"),
    ("how do I add a customer access review", "Customer Access Review"),
    ("what's a good label for a hanging vacuum", "Vacuum Hang Label"),
    ("how do I label an oauth redirect bug", "OAuth Redirect Label"),
    ("github include auth prompts", "Auth Prompts"),
    ("my webcam needs pipewire camera portal", "Pipewire Camera Portal"),
    ("how do I pick a visa for a press tour", "Press Tour Visa"),
    ("how do I keep leftover pho broth", "Leftover Pho Broth"),
    ("what's a good default win/loss reason capture", "Win Loss Capture"),
    ("how do I include api prompts", "API Prompts"),
    ("cloudflare workers websocket accept", "WebSocket Accept"),
    ("how do I add a customer entitlement check", "Entitlement Check"),
    ("what's a good label for a leaked pat", "Leaked PAT Label"),
    ("how do I label a d1 backup question", "D1 Backup Label"),
    ("the label should not be a sentence", "Label Not A Sentence"),
    ("how do I pick a visa for a film shoot", "Film Shoot Visa"),
    ("how do I keep leftover ramen toppings", "Leftover Ramen Toppings"),
    ("what's a good default competitor win rate", "Competitor Win Rate"),
    ("how do I include git prompts", "Git Prompts"),
    ("cloudflare workers hibernation api", "Hibernation API"),
    ("how do I add a customer rate limit dashboard", "Rate Limit Dashboard"),
    ("what's a good label for a zfs degraded pool", "ZFS Pool Label"),
    ("how do I label a wireguard setup question", "WireGuard Setup Label"),
    ("github include networking prompts", "Networking Prompts"),
    ("my webcam needs libcamera on pi", "libcamera Raspberry Pi"),
    ("how do I pick a visa for a location scout", "Location Scout Visa"),
    ("how do I keep leftover udon", "Leftover Udon"),
    ("what's a good default discount leakage", "Discount Leakage"),
    ("how do I include github prompts", "GitHub Prompts"),
    ("cloudflare workers partykit vs do", "PartyKit vs Durable Objects"),
    ("how do I add a customer usage cap email", "Usage Cap Email"),
    ("what's a good label for a hanging systemd unit", "Systemd Hang Label"),
    ("how do I label a nuxt i18n bug", "Nuxt i18n Label"),
    ("the completion is the label not a chat reply", "Completion Is Label"),
    ("how do I pick a visa for a recording session", "Recording Session Visa"),
    ("how do I keep leftover soba", "Leftover Soba"),
    ("what's a good default billed vs collected", "Billed vs Collected"),
    ("how do I include productivity prompts", "Productivity Prompts"),
    ("cloudflare workers actor model", "Workers Actor Model"),
    ("how do I add a customer dunning email", "Dunning Email"),
    ("what's a good label for a failed prisma migrate", "Prisma Migrate Label"),
    ("how do I label a cloudflare access setup", "Access Setup Label"),
    ("github include cloudflare prompts", "Cloudflare Prompts"),
    ("my webcam needs rpicam-hello", "Raspberry Pi Camera Hello"),
    ("how do I pick a visa for a studio visit", "Studio Visit Visa"),
    ("how do I keep leftover donburi", "Leftover Donburi"),
    ("what's a good default failed payment recovery", "Failed Payment Recovery"),
    ("how do I include business prompts", "Business Prompts"),
    ("cloudflare workers sqlite in durable objects", "DO SQLite"),
    ("how do I add a customer dunning cadence", "Dunning Cadence"),
    ("what's a good label for a leaked stripe key", "Stripe Key Label"),
    ("how do I label a passkey setup question", "Passkey Setup Label"),
    ("the user prompt can contain multiple concepts", "Multi Concept User"),
    ("how do I pick a visa for a gallery opening", "Gallery Opening Visa"),
    ("how do I keep leftover onigiri", "Leftover Onigiri"),
    ("what's a good default involuntary churn", "Involuntary Churn"),
    ("how do I include food prompts", "Food Prompts"),
    ("cloudflare workers sqlite do storage", "DO Storage SQLite"),
    ("how do I add a customer grace period", "Customer Grace Period"),
    ("what's a good label for a sour espresso", "Sour Espresso Label"),
    ("how do I label a sourdough starter problem", "Sourdough Label"),
    ("github include travel prompts", "Travel Prompts"),
    ("my webcam needs cheese --fullscreen", "cheese Fullscreen"),
    ("how do I pick a visa for a book tour", "Book Tour Visa"),
    ("how do I keep leftover bento", "Leftover Bento"),
    ("what's a good default voluntary churn", "Voluntary Churn"),
    ("how do I include shopping checkout questions", "Shopping Checkout"),
    ("cloudflare workers do sql migrations", "DO SQL Migrations"),
    ("how do I add a customer pause subscription", "Pause Subscription"),
    ("what's a good label for a tight layover", "Tight Layover Label"),
    ("how do I label a packing liquids question", "TSA Liquids Label"),
    ("the casual prompt still needs a serious label", "Casual Prompt Serious Label"),
    ("how do I pick a visa for a lecture series", "Lecture Series Visa"),
    ("how do I keep leftover katsu", "Leftover Katsu"),
    ("what's a good default logo expansion quarterly", "Quarterly Logo Expansion"),
    ("how do I include general knowledge questions", "General Questions"),
    ("cloudflare workers do alarms retries", "DO Alarm Retries"),
    ("how do I add a customer resume subscription", "Resume Subscription"),
    ("what's a good label for a mortgage refinance", "Mortgage Refinance Label"),
    ("how do I label a 401k versus debt question", "401k vs Debt Label"),
    ("github include finance questions", "Finance Questions"),
    ("my webcam needs snapshot from vlc", "VLC Webcam Snapshot"),
    ("how do I pick a visa for a keynote", "Keynote Visa"),
    ("how do I keep leftover gyoza", "Leftover Gyoza"),
    ("what's a good default expansion from usage", "Usage Based Expansion"),
    ("how do I include hardware troubleshooting", "Hardware Troubleshooting"),
    ("cloudflare workers do id from name", "Durable Object From Name"),
    ("how do I add a customer seat add on", "Seat Add On"),
    ("what's a good label for a clicking nas", "NAS Click Label"),
    ("how do I label a full ssd slowdown", "Full SSD Label"),
    ("the first message might have typos like pls help", "Typos Still Label"),
    ("how do I pick a visa for a panel", "Panel Visa"),
    ("how do I keep leftover takoyaki", "Leftover Takoyaki"),
    ("what's a good default expansion from seats", "Seat Based Expansion"),
    ("how do I include devops prompts", "DevOps Prompts"),
    ("cloudflare workers do get by name", "getByName Durable Object"),
    ("how do I add a customer storage add on", "Storage Add On"),
    ("what's a good label for a hanging vacuum analyze", "Vacuum Analyze Label"),
    ("how do I label a redis stampede", "Redis Stampede Label"),
    ("github include database prompts", "Database Prompts"),
    ("my webcam needs fswebcam", "fswebcam Capture"),
    ("how do I pick a visa for a workshop", "Workshop Visa"),
    ("how do I keep leftover okonomiyaki", "Leftover Okonomiyaki"),
    ("what's a good default expansion from modules", "Module Expansion"),
    ("how do I include web development prompts", "Web Development Prompts"),
    ("cloudflare workers do location hint", "DO Location Hint"),
    ("how do I add a customer support tier", "Support Tier Add On"),
    ("what's a good label for a cors debug", "CORS Debug Label"),
    ("how do I label a blank spa deploy", "Blank SPA Label"),
    ("the implicit prompt still maps to a subject", "Implicit Maps To Subject"),
    ("how do I pick a visa for a retreat", "Retreat Visa"),
    ("how do I keep leftover yakisoba", "Leftover Yakisoba"),
    ("what's a good default expansion from regions", "Region Expansion"),
    ("how do I include programming language prompts", "Programming Prompts"),
    ("cloudflare workers do jurisdiction", "DO Jurisdiction"),
    ("how do I add a customer dedicated tenant", "Dedicated Tenant Add On"),
    ("what's a good label for a hanging celery worker", "Celery Hang Label"),
    ("how do I label a sqlite locked db", "SQLite Locked Label"),
    ("github include agent prompts", "Agent Prompts"),
    ("my webcam needs mplayer tv://", "mplayer TV Capture"),
    ("how do I pick a visa for a residency program", "Residency Program Visa"),
    ("how do I keep leftover tempura from going soggy", "Leftover Tempura"),
    ("what's a good default expansion from api calls", "API Call Expansion"),
    ("how do I include llm prompts", "LLM Prompts"),
    ("cloudflare workers do sql exec", "Durable Object SQL Exec"),
    ("how do I add a customer audit export", "Audit Export"),
    ("what's a good label for an agent retry loop", "Agent Retry Label"),
    ("how do I label an mcp safety question", "MCP Safety Label"),
    ("the long prompt still yields a short label", "Long Prompt Short Label"),
    ("how do I pick a visa for a field study", "Field Study Visa"),
    ("how do I keep leftover karaage", "Leftover Karaage"),
    ("what's a good default expansion from storage", "Storage Expansion"),
    ("how do I include software architecture prompts", "Software Architecture Prompts"),
    ("cloudflare workers do storage put", "Durable Object Storage Put"),
    ("how do I add a customer sso add on", "SSO Add On"),
    ("what's a good label for a scim question", "SCIM Label"),
    ("how do I label a pkce setup", "PKCE Setup Label"),
    ("github include authentication prompts", "Authentication Prompts"),
    ("my webcam needs ffmpeg -f v4l2 -i /dev/video0", "ffmpeg video0"),
    ("how do I pick a visa for an excavation", "Excavation Visa"),
    ("how do I keep leftover tonkatsu sauce", "Leftover Tonkatsu Sauce"),
    ("what's a good default expansion from sms", "SMS Expansion"),
    ("how do I include ai agent prompts", "AI Agent Prompts"),
    ("cloudflare workers do storage get", "Durable Object Storage Get"),
    ("how do I add a customer saml add on", "SAML Add On"),
    ("what's a good label for oidc versus saml", "OIDC vs SAML Label"),
    ("how do I label a jwt rotation question", "JWT Rotation Label"),
    ("the short prompt docker networking still labels well", "Short Prompt Still Works"),
    ("how do I pick a visa for a conservation trip", "Conservation Trip Visa"),
    ("how do I keep leftover gyoza dipping sauce", "Leftover Dipping Sauce"),
    ("what's a good default expansion from seats unused", "Unused Seat Expansion"),
    ("how do I include docker compose prompts", "Docker Compose Prompts"),
    ("cloudflare workers do storage delete", "Durable Object Storage Delete"),
    ("how do I add a customer scim add on", "SCIM Add On"),
    ("what's a good label for a k8s oom", "K8s OOM Label"),
    ("how do I label a helm versus kustomize question", "Helm vs Kustomize Label"),
    ("github include k8s prompts", "Kubernetes Dataset"),
    ("my webcam needs cheese record", "cheese Record"),
    ("how do I pick a visa for a wildlife survey", "Wildlife Survey Visa"),
    ("how do I keep leftover edamame", "Leftover Edamame"),
    ("what's a good default expansion from support", "Support Expansion"),
    ("how do I include linux systemd prompts", "Systemd Prompts"),
    ("cloudflare workers do storage list", "Durable Object Storage List"),
    ("how do I add a customer sla add on", "SLA Add On"),
    ("what's a good label for a fail2ban setup", "Fail2ban Setup Label"),
    ("how do I label an nftables question", "nftables Label"),
    ("the everyday question still gets a title", "Everyday Gets A Title"),
    ("how do I pick a visa for a disaster relief trip", "Disaster Relief Visa"),
    ("how do I keep leftover mochi from hardening", "Leftover Mochi"),
    ("what's a good default expansion from training", "Training Seat Expansion"),
    ("how do I include shopping return questions", "Shopping Returns"),
    ("cloudflare workers do sql batch", "Durable Object SQL Batch"),
    ("how do I add a customer training add on", "Training Add On"),
    ("what's a good label for a double visa charge", "Visa Double Charge Label"),
    ("how do I label a net worth tracking question", "Net Worth Label"),
    ("github include everyday life prompts", "Everyday Life Prompts"),
    ("my webcam needs snapshot via gphoto2", "gphoto2 Snapshot"),
    ("how do I pick a visa for a reconstruction trip", "Reconstruction Trip Visa"),
    ("how do I keep leftover dango", "Leftover Dango"),
    ("what's a good default expansion from professional services", "Services Expansion"),
    ("how do I include food safety questions", "Food Safety Questions"),
    ("cloudflare workers do sql dump", "Durable Object SQL Dump"),
    ("how do I add a customer onboarding add on", "Onboarding Add On"),
    ("what's a good label for leftover rice safety", "Leftover Rice Label"),
    ("how do I label a carbonara question", "Carbonara Label"),
    ("the shopping prompt still extracts the product intent", "Shopping Intent Label"),
    ("how do I pick a visa for a humanitarian trip", "Humanitarian Trip Visa"),
    ("how do I keep leftover taiyaki", "Leftover Taiyaki"),
    ("what's a good default expansion from implementation", "Implementation Expansion"),
    ("how do I include travel packing questions", "Travel Packing"),
    ("cloudflare workers do sql exec named", "Named Durable Object SQL"),
    ("how do I add a customer success add on", "Customer Success Add On"),
    ("what's a good label for a schengen appointment", "Schengen Appointment Label"),
    ("how do I label a tokyo itinerary question", "Tokyo Itinerary Label"),
    ("github include travel packing and visas", "Travel Visa Prompts"),
    ("my webcam needs cheese burst mode", "cheese Burst"),
    ("how do I pick a visa for a peace corps type trip", "Peace Corps Type Visa"),
    ("how do I keep leftover dorayaki", "Leftover Dorayaki"),
    ("what's a good default expansion from solutions engineering", "Solutions Expansion"),
    ("how do I include hardware laptop questions", "Laptop Hardware Prompts"),
    ("cloudflare workers do sql ingest", "DO sql Ingest"),
    ("how do I add a customer dedicated slack", "Dedicated Slack Add On"),
    ("what's a good label for a screaming laptop fan", "Laptop Fan Label"),
    ("how do I label a keyboard double type", "Keyboard Double Type"),
    ("the hardware prompt is still a label not a repair manual", "Hardware Gets A Label"),
    ("how do I pick a visa for a missionary trip", "Missionary Trip Visa"),
    ("how do I keep leftover castella", "Leftover Castella"),
    ("what's a good default expansion from premium support", "Premium Support Expansion"),
    ("how do I include business process questions", "Business Process Prompts"),
    ("cloudflare workers do sql migrate", "DO sql Migrate"),
    ("how do I add a customer named engineer", "Named Engineer Add On"),
    ("what's a good label for a standup format", "Standup Format Label"),
    ("how do I label a salary negotiation question", "Salary Negotiation Label"),
    ("github include business and saas metrics", "SaaS Metrics Prompts"),
    ("my webcam needs ffmpeg drawtext overlay", "ffmpeg Overlay Webcam"),
    ("how do I pick a visa for an ngo assignment", "NGO Assignment Visa"),
    ("how do I keep leftover melonpan", "Leftover Melonpan"),
    ("what's a good default expansion from compliance", "Compliance Expansion"),
    ("how do I include saas pricing questions", "SaaS Pricing Prompts"),
    ("cloudflare workers do sql rollback", "DO sql Rollback"),
    ("how do I add a customer hipaa add on", "HIPAA Add On"),
    ("what's a good label for arr versus mrr", "ARR vs MRR Label"),
    ("how do I label a cap table question", "Cap Table Label"),
    ("the finance prompt still stays two to five words", "Finance Label Length"),
    ("how do I pick a visa for a medical residency observership", "Observership Visa"),
    ("how do I keep leftover anpan", "Leftover Anpan"),
    ("what's a good default expansion from hipaa", "HIPAA Expansion"),
    ("how do I include productivity meeting questions", "Meeting Productivity"),
    ("cloudflare workers do sql vacuum", "DO sql Vacuum"),
    ("how do I add a customer soc2 packet", "SOC2 Packet"),
    ("what's a good label for a definition of done", "Definition of Done Label"),
    ("how do I label a postmortem question", "Postmortem Label"),
    ("github include troubleshooting across stacks", "Broad Troubleshooting"),
    ("my webcam needs cheese video effect", "cheese Video Effect"),
    ("how do I pick a visa for a clinical trial visit", "Clinical Trial Visit Visa"),
    ("how do I keep leftover cream pan", "Leftover Cream Pan"),
    ("what's a good default expansion from soc2", "SOC2 Expansion"),
    ("how do I include general how does x work prompts", "How Does X Work"),
    ("cloudflare workers do sql analyze", "DO sql Analyze"),
    ("how do I add a customer pentest report share", "Pentest Report Share"),
    ("what's a good label for a hex architecture ask", "Hex Architecture Label"),
    ("how do I label an event sourcing intro", "Event Sourcing Label"),
    ("the architecture prompt is a subject not a lecture", "Architecture Subject Only"),
    ("how do I pick a visa for a hospital rotation", "Hospital Rotation Visa"),
    ("how do I keep leftover curry bread", "Leftover Curry Bread"),
    ("what's a good default expansion from pentest", "Pentest Expansion"),
    ("how do I include mcp versus tool questions", "MCP vs Tools"),
    ("cloudflare workers do sql pragma", "DO sql Pragma"),
    ("how do I add a customer questionnaire response", "Security Questionnaire"),
    ("what's a good label for mcp tools versus resources", "MCP Tools Resources"),
    ("how do I label an agent tool loop", "Agent Tool Loop Label"),
    ("github include ai llm agent mcp", "AI Stack Prompts"),
    ("my webcam needs cheese countdown 3", "cheese Countdown Three"),
    ("how do I pick a visa for a lab visit", "Lab Visit Visa"),
    ("how do I keep leftover yakisoba pan", "Leftover Yakisoba Pan"),
    ("what's a good default expansion from questionnaires", "Questionnaire Expansion"),
    ("how do I include programming language errors", "Language Error Prompts"),
    ("cloudflare workers do sql explain", "DO sql Explain"),
    ("how do I add a customer trust center", "Trust Center"),
    ("what's a good label for a typescript generic error", "TypeScript Generics Label"),
    ("how do I label a ruff pre commit setup", "Ruff Pre Commit Label"),
    ("the programming prompt still gets a short title", "Programming Short Title"),
    ("how do I pick a visa for a factory audit", "Factory Audit Visa"),
    ("how do I keep leftover korokke", "Leftover Korokke"),
    ("what's a good default expansion from trust center", "Trust Center Expansion"),
    ("how do I include web styling bugs", "Web Styling Bugs"),
    ("cloudflare workers do sql index", "DO sql Index"),
    ("how do I add a customer dpa signing", "DPA Signing"),
    ("what's a good label for tailwind not applying", "Tailwind Issue Label"),
    ("how do I label a nuxt hydration bug", "Nuxt Hydration Label"),
    ("github include web and nuxt", "Web Nuxt Prompts"),
    ("my webcam needs cheese crop", "cheese Crop"),
    ("how do I pick a visa for a warehouse visit", "Warehouse Visit Visa"),
    ("how do I keep leftover menchi katsu", "Leftover Menchi Katsu"),
    ("what's a good default expansion from legal review", "Legal Review Expansion"),
    ("how do I include api design questions", "API Design Prompts"),
    ("cloudflare workers do sql unique", "DO sql Unique"),
    ("how do I add a customer msa redline", "MSA Redline"),
    ("what's a good label for openapi writing", "OpenAPI Writing Label"),
    ("how do I label rest versus grpc", "REST vs gRPC Label"),
    ("the api prompt extracts protocol or design", "API Subject Extract"),
    ("how do I pick a visa for a shipyard visit", "Shipyard Visit Visa"),
    ("how do I keep leftover croquette", "Leftover Croquette"),
    ("what's a good default expansion from msa work", "MSA Expansion"),
    ("how do I include git collaboration questions", "Git Collaboration"),
    ("cloudflare workers do sql check", "DO sql Check"),
    ("how do I add a customer sla redline", "SLA Redline"),
    ("what's a good label for a detached head", "Detached Head Label"),
    ("how do I label github environments", "GitHub Environments Label"),
    ("github include git and github actions", "Git GitHub Actions"),
    ("my webcam needs cheese resolution", "cheese Resolution"),
    ("how do I pick a visa for a mine visit", "Mine Visit Visa"),
    ("how do I keep leftover hamburger steak", "Leftover Hamburger Steak"),
    ("what's a good default expansion from sla legal", "SLA Legal Expansion"),
    ("how do I include ci cd questions", "CICD Prompts"),
    ("cloudflare workers do sql foreign", "DO sql Foreign"),
    ("how do I add a customer uptime report", "Uptime Report"),
    ("what's a good label for actions cache miss", "Actions Cache Label"),
    ("how do I label playwright in actions", "Playwright Actions Label"),
    ("the ci prompt still stays short", "CI Short Label"),
    ("how do I pick a visa for an oil platform visit", "Oil Platform Visa"),
    ("how do I keep leftover hamburger", "Leftover Hamburger"),
    ("what's a good default expansion from uptime sla", "Uptime SLA Expansion"),
    ("how do I include docker image questions", "Docker Image Prompts"),
    ("cloudflare workers do sql trigger", "DO sql Trigger"),
    ("how do I add a customer quarterly business review", "QBR Add On"),
    ("what's a good label for docker disk cleanup", "Docker Disk Label"),
    ("how do I label a multiarch build", "Multiarch Build Label"),
    ("github include docker questions", "Docker Questions"),
    ("my webcam needs cheese brightness", "cheese Brightness"),
    ("how do I pick a visa for a refinery visit", "Refinery Visit Visa"),
    ("how do I keep leftover hayashi rice", "Leftover Hayashi Rice"),
    ("what's a good default expansion from qbr", "QBR Expansion"),
    ("how do I include kubernetes networking", "K8s Networking Prompts"),
    ("cloudflare workers do sql view", "DO sql View"),
    ("how do I add a customer exec sponsor", "Exec Sponsor Add On"),
    ("what's a good label for secret rotation in k8s", "K8s Secret Rotation"),
    ("how do I label a sidecar proxy question", "Sidecar Proxy Label"),
    ("the devops prompt extracts the tool and the action", "DevOps Tool Action"),
    ("how do I pick a visa for a data center tour", "Data Center Tour Visa"),
    ("how do I keep leftover omurice", "Leftover Omurice"),
    ("what's a good default expansion from exec sponsor", "Exec Sponsor Expansion"),
    ("how do I include database restore questions", "Database Restore"),
    ("cloudflare workers do sql cte", "DO sql CTE"),
    ("how do I add a customer solution architect", "Solution Architect Add On"),
    ("what's a good label for a postgres sequence repair", "Sequence Repair Label"),
    ("how do I label hugepages for postgres", "Postgres Hugepages Label"),
    ("github include postgres sqlite redis", "Database Engine Prompts"),
    ("my webcam needs cheese contrast", "cheese Contrast"),
    ("how do I pick a visa for a colo visit", "Colo Visit Visa"),
    ("how do I keep leftover doria", "Leftover Doria"),
    ("what's a good default expansion from architect time", "Architect Time Expansion"),
    ("how do I include redis cache questions", "Redis Cache Prompts"),
    ("cloudflare workers do sql window", "DO sql Window"),
    ("how do I add a customer implementation manager", "Implementation Manager"),
    ("what's a good label for cache stampede", "Cache Stampede Label"),
    ("how do I label a hanging vacuum", "Hanging Vacuum Label"),
    ("the database prompt names the engine", "Database Engine In Label"),
    ("how do I pick a visa for a peering meeting", "Peering Meeting Visa"),
    ("how do I keep leftover gratin", "Leftover Gratin"),
    ("what's a good default expansion from implementation managers", "IM Expansion"),
    ("how do I include auth session questions", "Auth Session Prompts"),
    ("cloudflare workers do sql returning", "DO sql Returning"),
    ("how do I add a customer technical account manager", "TAM Add On"),
    ("what's a good label for session cookies versus jwt", "Sessions vs JWT Label"),
    ("how do I label step up auth", "Step Up Auth Label"),
    ("github include oauth oidc saml", "OAuth OIDC SAML"),
    ("my webcam needs cheese saturation", "cheese Saturation"),
    ("how do I pick a visa for an ietf meeting", "IETF Meeting Visa"),
    ("how do I keep leftover macaroni gratin", "Leftover Macaroni Gratin"),
    ("what's a good default expansion from tam", "TAM Expansion"),
    ("how do I include cloudflare product questions", "Cloudflare Product Prompts"),
    ("cloudflare workers do sql changes", "DO sql Changes"),
    ("how do I add a customer dedicated ip", "Dedicated IP Add On"),
    ("what's a good label for durable objects", "Durable Objects Label"),
    ("how do I label hyperdrive to neon", "Hyperdrive Neon Label"),
    ("the cloudflare prompt names the product", "Cloudflare Product Label"),
    ("how do I pick a visa for a standards meeting", "Standards Meeting Visa"),
    ("how do I keep leftover doria leftovers two days", "Two Day Doria"),
    ("what's a good default expansion from dedicated ip", "Dedicated IP Expansion"),
    ("how do I include networking wifi questions", "Wifi Networking Prompts"),
    ("cloudflare workers do sql lastInsertRowId", "SQL Last Insert Row"),
    ("how do I add a customer private connectivity", "Private Connectivity Add On"),
    ("what's a good label for microwave wifi drops", "Wifi Microwave Label"),
    ("how do I label ipv6 broken ipv4 works", "IPv6 Issue Label"),
    ("github include networking troubleshooting", "Networking Troubleshooting"),
    ("my webcam needs cheese hue", "cheese Hue"),
    ("how do I pick a visa for a hacker camp", "Hacker Camp Visa"),
    ("how do I keep leftover pizza bread", "Leftover Pizza Bread"),
    ("what's a good default expansion from private link", "Private Link Expansion"),
    ("how do I include llm eval questions", "LLM Eval Prompts"),
    ("cloudflare workers do sql rowsWritten", "SQL Rows Written"),
    ("how do I add a customer vpc peering", "VPC Peering Add On"),
    ("what's a good label for prompt evals", "Prompt Eval Label"),
    ("how do I label catastrophic forgetting", "Forgetting Label"),
    ("the ai prompt still must not become a tutorial", "AI Prompt Short Label"),
    ("how do I pick a visa for a ctf", "CTF Visa"),
    ("how do I keep leftover garlic naan", "Leftover Garlic Naan"),
    ("what's a good default expansion from vpc", "VPC Expansion"),
    ("how do I include local model packaging questions", "Local Model Packaging"),
    ("cloudflare workers do sql rowsRead", "SQL Rows Read"),
    ("how do I add a customer bring your own key", "BYOK Add On"),
    ("what's a good label for ollama packaging", "Ollama Package Label"),
    ("how do I label a gguf convert question", "GGUF Convert Label"),
    ("github include ollama llama cpp", "Ollama llamacpp Prompts"),
    ("my webcam needs cheese zoom", "cheese Zoom"),
    ("how do I pick a visa for a lock-in", "Hackathon Lockin Visa"),
    ("how do I keep leftover cheese naan", "Leftover Cheese Naan"),
    ("what's a good default expansion from byok", "BYOK Expansion"),
    ("how do I include small model training questions", "Small Model Training"),
    ("cloudflare workers do sql size", "DO sql Size"),
    ("how do I add a customer key management", "KMS Add On"),
    ("what's a good label for lora merge", "LoRA Merge Label"),
    ("how do I label qlora for 135m", "QLoRA 135M Label"),
    ("the training prompt extracts the method not a recipe dump", "Training Method Label"),
    ("how do I pick a visa for an onsite sprint", "Onsite Sprint Visa"),
    ("how do I keep leftover keema naan", "Leftover Keema Naan"),
    ("what's a good default expansion from kms", "KMS Expansion"),
    ("how do I include bros specific operator questions", "Bros Operator Prompts"),
    ("cloudflare workers do sql quota", "DO sql Quota"),
    ("how do I add a customer encryption at rest proof", "Encryption At Rest Proof"),
    ("what's a good label for installing bros from git", "Install Bros Git"),
    ("how do I label a missing gguf install failure", "Missing GGUF Label"),
    ("github include this project as examples too", "Project Meta Prompts"),
    ("pls help docker compose postgres volume empty after reboot", "Compose Volume Empty"),
    ("hey my wrangler deploy says binding not found what now", "Wrangler Binding Missing"),
    ("k8s ingress or a cloudflare tunnel for a homelab", "Homelab Ingress Choice"),
    ("uv pin a package without a lockfile fight", "uv Pin Package"),
    ("why does nvidia-smi fail inside this container", "nvidia smi In Container"),
    ("need a quiet 2 day lisbon plan with one museum max", "Lisbon Two Day Plan"),
    ("budget app that doesn't make me feel guilty", "Guilt Free Budget App"),
    ("mechanical keyboard chatters on one key only", "Single Key Chatter"),
    ("explain workers kv like I know redis already", "KV for Redis Users"),
    ("got a leaked github token in a screenshot yikes", "Leaked Token Screenshot"),
]

def unique_pairs() -> list[tuple[str, str]]:
    seen_prompts: set[str] = set()
    seen_labels_prompt: set[tuple[str, str]] = set()
    out: list[tuple[str, str]] = []
    for prompt, label in PAIRS:
        prompt = prompt.strip()
        label = label.strip()
        if prompt in seen_prompts:
            continue
        key = (prompt, label)
        if key in seen_labels_prompt:
            continue
        seen_prompts.add(prompt)
        seen_labels_prompt.add(key)
        out.append((prompt, label))
    return out


def main() -> None:
    pairs = unique_pairs()
    if len(pairs) < 1000:
        raise SystemExit(f"need ~1000 unique examples, got {len(pairs)}")
    rng = random.Random(42)
    # Light casing jitter on a subset; keep the original unique prompt text otherwise.
    rows = []
    for prompt, label in pairs:
        tagged = f"Label: {prompt}"
        rows.append({"prompt": tagged, "completion": label, "task": "label"})
    rng.shuffle(rows)
    # Restore deterministic order via seed shuffle then write in that order;
    # prepare-data.shuffles again with the same seed after validation.
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"wrote {len(rows)} rows to {OUT}")


if __name__ == "__main__":
    main()
